version: "3.9"

services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: asegan
      POSTGRES_PASSWORD: asega@1965
      POSTGRES_DB: comet
    ports: ["5432:5432"]
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U asegan -d comet"]
      interval: 5s
      timeout: 5s
      retries: 20

  api:
    build: ./backend
    env_file: ./.env
    depends_on:
      db:
        condition: service_healthy
    ports: ["8000:8000"]
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    volumes:
      - ./backend:/app

  web:
    build: ./frontend
    env_file: ./.env
    depends_on:
      - api
    ports: ["3000:3000"]
    command: ["npm", "run", "dev"]
    volumes:
      - ./frontend:/usr/src/app

volumes:
  db_data:
