name: CI Frontend
on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - '.github/workflows/ci-frontend.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - '.github/workflows/ci-frontend.yml'

jobs:
  lint-test-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install
        working-directory: frontend
        run: npm ci || npm i

      - name: Lint
        working-directory: frontend
        run: npm run lint

      # Si vous gardez Vitest :
      - name: Tests (vitest)
        working-directory: frontend
        run: npm run test --if-present

      # Audit visible mais non bloquant (high seulement)
      - name: Audit (high only)
        working-directory: frontend
        run: npm audit --audit-level=high || true

      - name: Build
        working-directory: frontend
        run: npm run build
